### ISSUE TITLE
특수문자 사용시 오류 발생

### ISSUE THREAD

**Issue by jh05013** [dodok8/discord-aladin#9]
다음 검색어를 사용할 시 `검색 중 오류 발생` 오류가 발생합니다:
- `&`
- `#`

**Comment by dodok8** [comment]
`#` 검색어 어디에 포함되어도 오류가 난다는 제보도 있었습니다. 이 부분은 최대한 빠르게 고치겠습니다.

**Comment by dodok8** [comment]
오류 원인
- #`은 알라딘에서 검색어로 처리되지 않습니다.(사용자가 직접 검색창에 입력해도 그럼)
- API에서는 `#` 이 입력되면 그 이후 문자열이 아예 인식이 안 되는 버그가 있습니다.(버그라고 하긴 좀 그렇고, 앵커로 인식되는 걸로 추정)
- 검색 키워드 이후 쿼리에, 응답 형식을 정의하는 쿼리가 있었기 때문에 이 쿼리가 무시되고 기본값인 xml로 반환이 되었고, 이를 파싱하는데 실패하여 전체가 죽었습니다.

**Comment by dodok8** [comment]
이는 결국 `encodeURI` 가 원하는 대로 작동 안 한다는 걸 의미하고, 방금 실제로도 작동안하는 걸 확인했습니다. 찾아보니 `encodeURIComponent` 라는 게 있네요.
